package interfaz;

public class InformacionCiclista extends javax.swing.JDialog {

    /**
     * Inicia un nuevo JDialog para desplegar información de un ciclista.
     * @param c Objeto de tipo Ciclista del cual se va a desplegar la información.
     */
    public InformacionCiclista(java.awt.Frame parent, boolean modal, modelo.Ciclista c) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setTitle("Información del ciclista");
        this.setResizable(false);
        String[] info = c.toString().split(",");
        this.identificacion.setText(info[0]);
        this.nombre.setText(info[1]);
        this.apellido.setText(info[2]);
        this.sexo.setText(info[3]);
        this.edad.setText(info[4]);
        String[] f = info[5].split("-");
        this.fechaNacimiento.setText(f[2]+"-"+f[1]+"-"+f[0]);
        this.idAtleta.setText(info[6]);
        this.nivel.setText(info[7]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        identificacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idAtleta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("N° Identificación:");

        identificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        identificacion.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombre.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Apellido:");

        apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        apellido.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Sexo:");

        sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sexo.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Edad:");

        edad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edad.setText(" ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Fecha de nacimiento:");

        fechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaNacimiento.setText(" ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("N° ID Atleta:");

        idAtleta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idAtleta.setText(" ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nivel:");

        nivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nivel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificacion)
                    .addComponent(nombre)
                    .addComponent(apellido)
                    .addComponent(sexo)
                    .addComponent(edad)
                    .addComponent(fechaNacimiento)
                    .addComponent(idAtleta)
                    .addComponent(nivel))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(identificacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sexo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaNacimiento)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(idAtleta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nivel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel fechaNacimiento;
    private javax.swing.JLabel idAtleta;
    private javax.swing.JLabel identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
