package interfaz;

import java.util.Arrays;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import modelo.Rutina;

public class VisualizarDatos extends javax.swing.JDialog {

    /**
     * Inicia un nuevo JDialog para visualizar los datos registrados hasta el momento.
     */
    public VisualizarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Visualizar datos");
        this.setLocationRelativeTo(null);
        fecha.setEditor(new JSpinner.DateEditor(fecha,"dd/MM/yyyy"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        visualizarButton = new javax.swing.JButton();
        fecha = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        todasFechas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fecha de práctica:");

        visualizarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        visualizarButton.setText("Visualizar reporte");
        visualizarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1104555660000L), new java.util.Date(), java.util.Calendar.MONTH));
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaMouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "ID Ciclista", "Tiempo 1", "Tiempo 2", "Tiempo 3"
            }
        ));
        jScrollPane1.setViewportView(table);

        todasFechas.setText("Todas las fechas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todasFechas)
                .addGap(23, 23, 23)
                .addComponent(visualizarButton)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todasFechas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción del botón Visualizar reporte
     */
    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed
        Date d = (Date)fecha.getValue();
        String f = String.valueOf(d.getYear()+1900)+"-";
        if(d.getMonth() < 9){
            f += "0"+String.valueOf(d.getMonth()+1);
        }
        else {
            f += String.valueOf(d.getMonth()+1);
        }
        f += "-"+String.valueOf(d.getDate());
        DefaultTableModel tblModel = (DefaultTableModel)table.getModel();
        tblModel.setRowCount(0);
        for (String linea : Rutina.rutinas){
            String[] data = linea.split(",");
            String[] df = Arrays.copyOfRange(data, 0, 5);
            if (todasFechas.isSelected()){
                tblModel.addRow(df);
            }
            else if (data[0].equals(f)){
                tblModel.addRow(df);
            }
        }
        todasFechas.setSelected(false);
    }//GEN-LAST:event_visualizarButtonActionPerformed

    private void fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMouseClicked
    }//GEN-LAST:event_fechaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JCheckBox todasFechas;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables
}
